config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'meetings#index'

  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/allocation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: allocations
#
#  id         :bigint           not null, primary key
#  meeting_id :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_allocations_on_meeting_id  (meeting_id)
#  index_allocations_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (meeting_id => meetings.id)
#  fk_rails_...  (user_id => users.id)
#
class Allocation < ApplicationRecord
  belongs_to :meeting
  belongs_to :user

  scope :with_current_meetings, (lambda do
    joins(:meeting).merge(Meeting.current)
  end)

  scope :with_past_meetings, (lambda do
    joins(:meeting).merge(Meeting.past)
  end)
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: departments
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Department < ApplicationRecord
  has_many :users

  validates_presence_of :name
end

app/models/meeting.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: meetings
#
#  id         :bigint           not null, primary key
#  month      :integer          not null
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Meeting < ApplicationRecord
  FORBIDDEN_PAIRS_PERIOD_IN_MONTHS = 3

  has_many :allocations
  has_many :users, through: :allocations

  validates_presence_of :year, :month

  scope :current, -> { where('year = ? AND month = ?', Date.current.year, Date.current.month) }

  scope :past, (lambda do
    where('(year = ? AND month < ?) OR year < ?', Date.current.year, Date.current.month, Date.current.year)
  end)
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  role            :integer          default("user"), not null
#  state           :integer          default("active"), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  department_id   :bigint
#
# Indexes
#
#  index_users_on_department_id  (department_id)
#
# Foreign Keys
#
#  fk_rails_...  (department_id => departments.id)
#
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password
  has_one_attached :avatar

  belongs_to :department

  has_many :allocations
  has_many :meetings, through: :allocations

  enum state: { active: 0, inactive: 1 }
  enum role: { user: 0, admin: 1 }

  validates_presence_of :name, :state, :department, :role
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  scope :active, -> { where(state: :active) }

  def active?
    state == 'active'
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'

    redirect_to login_url
  end
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  def index
    collection =
      if request.xhr?
        MeetingsSearcher.new(params, Allocation.all).call
      else
        Allocation
          .with_current_meetings
          .includes(:meeting, user: :department)
          .includes(user: { avatar_attachment: :blob })
      end

    @data = MeetingsDatatable.new(view_context, collection).call

    respond_to do |format|
      format.html
      format.json { render json: @data }
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user =
      User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in user

      redirect_back_or users_url
    else
      flash.now[:danger] = 'Invalid email/password combination'

      render 'new'
    end
  end

  def destroy
    log_out

    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, :verify_role

  def index
    @users =
      User
      .all
      .includes(:department, avatar_attachment: :blob)
      .order(id: :desc)
      .paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UsersManager.new.add_new_user(@user.id)

      flash[:success] = 'User was successfully created.' # Nice to tmplement it with i18n
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'User was successfully updated.'

      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.update(state: :inactive)
      UsersManager.new.delete_from_meeting(@user.id)

      flash[:success] = 'User was deactivated.'
    end

    redirect_to @user
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:name, :email, :password, :password_confirmation, :department_id, :role, :state, :avatar)
      .then do |permitted|
        permitted.delete(:password) unless permitted[:password].present?
        permitted.delete(:password_confirmation) unless permitted[:password_confirm].present?

        permitted
      end
  end

  def verify_role
    return if current_user.admin?

    flash[:alert] = 'You cannot access this resource.'

    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def avatar_for(user)
    return gravatar(user) unless user.avatar.present?

    image_tag user.avatar.variant(resize: "75x75")
  end

  def gravatar(user)
    image_tag("#{ENV['GRAVATAR_URL']}?gravatar_id=#{Digest::MD5::hexdigest(user.email)}?d=wavatar")
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar mb-2">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
     <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", login_path %></li>
      </ul>
     <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MysteryLunch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/index.html.erb
<div class="page-header">
  <h3> Mystery lunches </h3>
</div>

<tr>
  <td>Filter: </td>
  <td><input name="current" type="radio" id="current" value="current" checked="checked">Current month</td>
  <td><input name="current" type="radio" id="past" value="past">Past months</td>
</tr>

<table id="meetings-table" class="table table-bordered" data-source="<%= root_url(format: "json") %>">
  <thead>
    <tr>
      <th> Id </th>
      <th> Month </th>
      <th> Name </th>
      <th> Department </th>
      <th> Avatar </th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class='text-danger'><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
  <%= render 'error_messages' %>

  <div class="form-group">
    <%= f.label :avatar, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :avatar, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password_confirmation, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :department, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :department_id, options_for_select(Department.all.map { |d| [d.name, d.id.to_i] }, @user.department_id), :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, :class => 'btn btn-info' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                users_path, class: 'btn btn-light' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:department) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.department.name %></td>
        <td><%= user.state %></td>
        <td><%= user.role %></td>
        <td><%= avatar_for(user) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-info btn-xs' %>

          <% if user.active? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_user_path(user), :class => 'btn btn-info btn-xs' %>

            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= avatar_for(@user) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @user.role %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @user.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:department) %>:</strong></dt>
  <dd><%= @user.department.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-info'  %>

<% if @user.active? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_user_path(@user), :class => 'btn btn-info' %>

  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                user_path(@user),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>